name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download latest ngrok
        run: Invoke-WebRequest https://bin.equinox.io/a/g95kFjtk3kB/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

      - name: Extract ngrok
        run: Expand-Archive ngrok.zip -DestinationPath ngrok

      - name: Auth with ngrok
        run: .\ngrok\ngrok.exe config add-authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Enable RDP (Remote Desktop)
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name 'DenyTSConnections' -Value 0
          Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name 'UserAuthentication' -Value 1
          Set-LocalUser -Name 'runneradmin' -Password (ConvertTo-SecureString 'P@ssw0rd!' -AsPlainText -Force)

      - name: Start ngrok tunnel
        run: .\ngrok\ngrok.exe tcp 3389
